# Suppress warnings. These are caused by the gateway in front of the test server
import warnings
warnings.filterwarnings('ignore')

# Raise the logging level to error, to ignore any warnings generated by the over-cleaned RS database
import logging
logging.getLogger().setLevel(logging.ERROR)
