name: Pre-merge checks (dependabot)

# Run only on main branch. This avoids duplicated actions on PRs
on:
  pull_request:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    if: startsWith( github.event.pull_request.head.ref, 'dependabot/')
    uses: ./.github/workflows/ci_cd_reusable.yml
