on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

env:
  MAIN_PYTHON_VERSION: '3.9'

jobs:
  style:
    name: Code Style Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install style requirements
        run: pip install 'tox<4' poetry --disable-pip-version-check

      - name: Spell, Lint and Type Check
        run: tox -e style


  docs-style:
    name: Documentation Style Check
    runs-on: ubuntu-latest
    steps:
      - name: PyAnsys documentation style checks
        uses: pyansys/actions/doc-style@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]
    steps:
      - uses: actions/checkout@v3

      - name: Install kerberos headers
        run: sudo apt install libkrb5-dev

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install poetry 'tox<4' --disable-pip-version-check

      - name: Test with tox (no integration tests)
        run: tox -- -m "not integration"

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  package:
    name: Build package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ env.MAIN_PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: Create wheel
        run: |
          pip install poetry --disable-pip-version-check
          poetry build

      - name: Validate wheel
        run: |
          pip install twine --disable-pip-version-check
          twine check dist/*

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v3
        with:
          name: ansys-grantami-bomanalytics-wheel
          path: dist/
          retention-days: 7

  docs-no-examples:
    name: Build HTML documentation without examples
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ env.MAIN_PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install libkrb5-dev
          sudo apt install pandoc

      - name: Install library
        run: |
          pip install poetry --disable-pip-version-check
          poetry install --with doc

      - name: Build HTML Documentation
        run: make -C doc html SPHINXOPTS="-W"

      - name: Upload HTML Documentation
        uses: actions/upload-artifact@v3
        with:
          name: Documentation-html-no-examples
          path: doc/build/html
          retention-days: 7
