name: Release

# Run only once integration tests have passed
on:
  workflow_run:
    workflows: ["Integration tests"]
    types:
      - completed

jobs:
  Release:
    if: contains(github.ref, 'refs/tags') && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # used for documentation deployment
      - name: Get Bot Application Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.BOT_APPLICATION_ID }}
          application_private_key: ${{ secrets.BOT_APPLICATION_PRIVATE_KEY }}

      - uses: actions/download-artifact@v2
        with:
          name: ansys-grantami-bomanalytics-wheel
          path: ~/dist

      - uses: actions/download-artifact@v2
        with:
          name: Documentation-pdf

      - uses: actions/download-artifact@v2
        with:
          name: Documentation-html
          path: ~/html

# Deleted actual release steps while testing

